name: kouroshyar
description: KouroshYar - secure legal assistant Android build package.
publish_to: "none"
version: 3.6.59+131
environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  syncfusion_flutter_pdf: 33.2.7
  syncfusion_flutter_pdfviewer: 33.2.7
  share_plus: ^10.0.2
  cross_file: ^0.3.4+2
  open_filex: ^4.7.0
  local_auth: ^2.3.0
  crypto: ^3.0.7
  cryptography: 2.9.0
  archive: 3.6.1
  flutter_local_notifications: 22.0.1
  timezone: 0.11.1
  flutter_timezone: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
